// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voting.Infrastructure.Database;

#nullable disable

namespace Voting.Infrastructure.Migrations
{
    [DbContext(typeof(VotingDbContext))]
    partial class VotingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("MessageId", "ConsumerId");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", (string)null);
                });

            modelBuilder.Entity("Voting.Domain.Entities.Poll", b =>
                {
                    b.Property<Guid>("PollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiresEligibilityCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PollId");

                    b.ToTable("Polls", (string)null);

                    b.HasData(
                        new
                        {
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Question = "Która architektura jest najwydajniejsza dla systemu głosowania?",
                            RequiresEligibilityCheck = true
                        },
                        new
                        {
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Question = "Który kanał aktualizacji wyników najlepiej wspiera aplikacje czasu rzeczywistego?",
                            RequiresEligibilityCheck = true
                        },
                        new
                        {
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Question = "Która strategia obsługi przeciążenia jest najbardziej akceptowalna dla użytkownika?",
                            RequiresEligibilityCheck = true
                        });
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollOption", b =>
                {
                    b.Property<Guid>("PollOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PollOptionId");

                    b.HasIndex("PollId");

                    b.ToTable("PollOptions", (string)null);

                    b.HasData(
                        new
                        {
                            PollOptionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OrderIndex = 1,
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Synchroniczna (API)"
                        },
                        new
                        {
                            PollOptionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OrderIndex = 2,
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Asynchroniczna (Event-Driven)"
                        },
                        new
                        {
                            PollOptionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OrderIndex = 3,
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Hybrydowa (Core Sync + Async Side Effects)"
                        },
                        new
                        {
                            PollOptionId = new Guid("21111111-1111-1111-1111-111111111111"),
                            OrderIndex = 1,
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Natychmiastowy odczyt z bazy"
                        },
                        new
                        {
                            PollOptionId = new Guid("22221111-1111-1111-1111-111111111111"),
                            OrderIndex = 2,
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "SignalR po aktualizacji projekcji"
                        },
                        new
                        {
                            PollOptionId = new Guid("22222211-1111-1111-1111-111111111111"),
                            OrderIndex = 3,
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Odświeżanie okresowe"
                        },
                        new
                        {
                            PollOptionId = new Guid("31111111-1111-1111-1111-111111111111"),
                            OrderIndex = 1,
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Kolejkowanie i późniejsze przetworzenie"
                        },
                        new
                        {
                            PollOptionId = new Guid("33311111-1111-1111-1111-111111111111"),
                            OrderIndex = 2,
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Odrzucenie nadmiaru żądań"
                        },
                        new
                        {
                            PollOptionId = new Guid("33333111-1111-1111-1111-111111111111"),
                            OrderIndex = 3,
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Text = "Spowolnienie odpowiedzi synchronicznej"
                        });
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollOptionResultsProjection", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("PollId", "PollOptionId");

                    b.ToTable("PollOptionResultsProjections", (string)null);

                    b.HasData(
                        new
                        {
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OptionText = "Synchroniczna (API)",
                            OrderIndex = 1,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OptionText = "Asynchroniczna (Event-Driven)",
                            OrderIndex = 2,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OptionText = "Hybrydowa (Core Sync + Async Side Effects)",
                            OrderIndex = 3,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("21111111-1111-1111-1111-111111111111"),
                            OptionText = "Natychmiastowy odczyt z bazy",
                            OrderIndex = 1,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("22221111-1111-1111-1111-111111111111"),
                            OptionText = "SignalR po aktualizacji projekcji",
                            OrderIndex = 2,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("22222211-1111-1111-1111-111111111111"),
                            OptionText = "Odświeżanie okresowe",
                            OrderIndex = 3,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("31111111-1111-1111-1111-111111111111"),
                            OptionText = "Kolejkowanie i późniejsze przetworzenie",
                            OrderIndex = 1,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("33311111-1111-1111-1111-111111111111"),
                            OptionText = "Odrzucenie nadmiaru żądań",
                            OrderIndex = 2,
                            VoteCount = 0
                        },
                        new
                        {
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            PollOptionId = new Guid("33333111-1111-1111-1111-111111111111"),
                            OptionText = "Spowolnienie odpowiedzi synchronicznej",
                            OrderIndex = 3,
                            VoteCount = 0
                        });
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollResultsProjection", b =>
                {
                    b.Property<Guid>("PollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PollTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.HasKey("PollId");

                    b.ToTable("PollResultsProjections", (string)null);

                    b.HasData(
                        new
                        {
                            PollId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            LastUpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PollTitle = "Która architektura jest najwydajniejsza dla systemu głosowania?",
                            TotalVotes = 0
                        },
                        new
                        {
                            PollId = new Guid("b1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            LastUpdatedAtUtc = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PollTitle = "Który kanał aktualizacji wyników najlepiej wspiera aplikacje czasu rzeczywistego?",
                            TotalVotes = 0
                        },
                        new
                        {
                            PollId = new Guid("c1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            LastUpdatedAtUtc = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PollTitle = "Która strategia obsługi przeciążenia jest najbardziej akceptowalna dla użytkownika?",
                            TotalVotes = 0
                        });
                });

            modelBuilder.Entity("Voting.Domain.Entities.VoteAuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex(new[] { "LoggedAtUtc" }, "IX_VoteAuditLogs_LoggedAtUtc");

                    b.HasIndex(new[] { "PollId" }, "IX_VoteAuditLogs_PollId");

                    b.HasIndex(new[] { "VoteId" }, "IX_VoteAuditLogs_VoteId")
                        .IsUnique();

                    b.ToTable("VoteAuditLogs", (string)null);
                });

            modelBuilder.Entity("Voting.Domain.Entities.VoteRecord", b =>
                {
                    b.Property<Guid>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Counted");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("VoteId");

                    b.HasIndex("PollOptionId");

                    b.HasIndex(new[] { "PollId" }, "IX_Votes_PollId");

                    b.HasIndex(new[] { "PollId", "UserId" }, "IX_Votes_PollId_UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("Voting.Domain.Entities.VoteSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("BrokerSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EndToEndLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("HttpResponseLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("QueueDelayMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("WorkerExecutionLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("WorkerStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex(new[] { "Status" }, "IX_VoteSubmissions_Status");

                    b.ToTable("VoteSubmissions", (string)null);
                });

            modelBuilder.Entity("Voting.Domain.Entities.VoterEligibility", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ChecksPerformed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilitySource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastCheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("VoterEligibilities", (string)null);
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollOption", b =>
                {
                    b.HasOne("Voting.Domain.Entities.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollOptionResultsProjection", b =>
                {
                    b.HasOne("Voting.Domain.Entities.PollResultsProjection", "PollResultsProjection")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollResultsProjection");
                });

            modelBuilder.Entity("Voting.Domain.Entities.VoteRecord", b =>
                {
                    b.HasOne("Voting.Domain.Entities.Poll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Domain.Entities.PollOption", "PollOption")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("PollOption");
                });

            modelBuilder.Entity("Voting.Domain.Entities.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Voting.Domain.Entities.PollResultsProjection", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
